"""initial persistent storage

Revision ID: 0001
Revises: 
Create Date: 2026-06-19 09:02:30.637312
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_audit_events_idempotency_key'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('source_bundle_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counts_json', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_import_jobs_idempotency_key'))
    )
    op.create_table('llm_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('automatic_application_performed', sa.Boolean(), nullable=False),
    sa.Column('live_model_verified', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_runs')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_llm_runs_fingerprint'))
    )
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('sha256', name=op.f('uq_source_documents_sha256'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('source_rows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('source_block', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.String(length=1024), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_source_rows_document_id_source_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_rows')),
    sa.UniqueConstraint('document_id', 'sheet_name', 'row_number', 'source_block', 'raw_hash', name='uq_source_rows_provenance')
    )
    with op.batch_alter_table('source_rows', schema=None) as batch_op:
        batch_op.create_index('ix_source_rows_document_sheet_row', ['document_id', 'sheet_name', 'row_number'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('import_job_id', sa.String(length=40), nullable=False),
    sa.Column('source_row_id', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.String(length=40), nullable=False),
    sa.Column('nomenclature_key', sa.String(length=512), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=255), nullable=False),
    sa.Column('grade_key', sa.String(length=255), nullable=False),
    sa.Column('dim1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dim2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dim3', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dim1_unit', sa.String(length=32), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_unit', sa.String(length=32), nullable=True),
    sa.Column('price_rub_kg', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reference_research_required', sa.Boolean(), nullable=False),
    sa.Column('reference_status', sa.String(length=64), nullable=True),
    sa.Column('automatic_application_performed', sa.Boolean(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_offers_import_job_id_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_row_id'], ['source_rows.id'], name=op.f('fk_offers_source_row_id_source_rows'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_offers_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_grade_key'), ['grade_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_nomenclature_key'), ['nomenclature_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_profile'), ['profile'], unique=False)
        batch_op.create_index('ix_offers_profile_grade', ['profile', 'grade_key'], unique=False)
        batch_op.create_index('ix_offers_review_flags', ['requires_review', 'reference_research_required'], unique=False)

    op.create_table('import_job_offers',
    sa.Column('import_job_id', sa.String(length=40), nullable=False),
    sa.Column('offer_id', sa.String(length=80), nullable=False),
    sa.Column('import_state', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_import_job_offers_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_import_job_offers_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('import_job_id', 'offer_id', name=op.f('pk_import_job_offers'))
    )
    op.create_table('reference_research_tasks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('offer_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_designation', sa.String(length=255), nullable=True),
    sa.Column('reference_status', sa.String(length=64), nullable=True),
    sa.Column('hints_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_reference_research_tasks_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_research_tasks')),
    sa.UniqueConstraint('offer_id', name=op.f('uq_reference_research_tasks_offer_id'))
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('offer_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('decision_status', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('previous_decision_id', sa.String(length=80), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_review_decisions_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_decision_id'], ['review_decisions.id'], name=op.f('fk_review_decisions_previous_decision_id_review_decisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_review_decisions_idempotency_key'))
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_review_decisions_offer_time', ['offer_id', 'decided_at'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('offer_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_review_items_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items')),
    sa.UniqueConstraint('offer_id', name=op.f('uq_review_items_offer_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_items')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_review_decisions_offer_time')

    op.drop_table('review_decisions')
    op.drop_table('reference_research_tasks')
    op.drop_table('import_job_offers')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offers_review_flags')
        batch_op.drop_index('ix_offers_profile_grade')
        batch_op.drop_index(batch_op.f('ix_offers_profile'))
        batch_op.drop_index(batch_op.f('ix_offers_nomenclature_key'))
        batch_op.drop_index(batch_op.f('ix_offers_grade_key'))
        batch_op.drop_index(batch_op.f('ix_offers_grade'))

    op.drop_table('offers')
    with op.batch_alter_table('source_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_source_rows_document_sheet_row')

    op.drop_table('source_rows')
    op.drop_table('suppliers')
    op.drop_table('source_documents')
    op.drop_table('llm_runs')
    op.drop_table('import_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index('ix_audit_events_created_at')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
